mitmedialab/gobo

- README.md
- server/config/configTemplate.py
-emphasize python 2 usage
-update config.py path
-change config template to have a postgres db url
> updated readme

- README.md
- server/scripts/clean_old_posts.py
> Fixing clean_old_posts script reliance on DATABASE_URL env var

- README.md
* Added instructions for NVM
* Moved Javascript build instructions to installation section
Fixes #66
> Document NVM 

- client/app/components/FacebookTwitterButtons/FacebookTwitterButtons.js
- server/scripts/queue_prioritized_user_posts.py
Fixes #73 
Aside: also fixed left over linting error in JS
> Fixed prioritized users criteria

- README.md
- manage.py
- migrations/alembic.ini
- release-tasks.sh
* updated documentation
* create and populate alembic_version table
Fixes #76
> Fixed DB update

- client/app/components/Nav/Nav.js
- client/app/constants/index.js
* Reordered menu
* Refactored navigation menu item creation
* Bumped version to 1.6.0
> Added privacy policy link to navigation menu

- client/app/components/App/app.scss
- client/app/components/FacebookTwitterButtons/FacebookTwitterButtons.js
- client/app/components/Login/Login.js
- client/app/components/Profile/Profile.js
- client/app/components/Profile/profile.scss
- client/app/components/Register/register.scss
- client/app/components/Register/registerSteps/RegisterSuccess.js
- client/app/components/Register/registerSteps/SelectPersona.js
- client/app/components/Register/registerSteps/SignupEmailPassword.js
- client/app/components/Register/registerSteps/SocialAuth.js
- client/app/constants/index.js
* fixed linting warnings
* refactored facebook twitter button components
* bump to v1.7.0
UI Changes:
In styling the page, I ran into situations where I had to go into another component in order to update the styles for the component I was trying to modify. There is for more modularity, and it would be worth considering something like https://github.com/css-modules/css-modules in the future.
> Added descriptions for Facebook and Twitter access

- client/app/actions/resetPassword.js
- client/app/components/App/App.js
- client/app/components/ForgotPassword/ForgotPassword.js
- client/app/components/Input/EmailInput.js
- client/app/components/Input/PasswordInput.js
- client/app/components/LockScreen/LockScreen.js
- client/app/components/Login/Login.js
- client/app/components/Profile/Profile.js
- client/app/components/Profile/profile.scss
- client/app/components/Register/Register.js
- client/app/components/Register/register.scss
- client/app/components/Register/registerSteps/SignupEmailPassword.js
- client/app/components/ResetPassword/ResetPassword.js
- client/app/components/SingleRegistrationWrapper/SingleRegistrationWrapper.js
- client/app/constants/index.js
- client/app/reducers/index.js
- client/app/reducers/resetPassword.js
- client/app/utils/apiRequests.js
- requirements/common.txt
- server/config/configTemplate.py
- server/core.py
- server/factory.py
- server/models.py
- server/templates/email/forgot-password.html
- server/utils.py
- server/views/auth.py
- server/views/home.py
* Refactored email & password inputs
* Added endpoints for token generation and password update
* Refactored User model to automatically encrypt password
TODO
Fixes #69
> Added password reset

- client/app/reducers/auth.js
> Replaced Object.assign with spread operator

- client/app/components/Settings/Settings.js
- client/app/components/Settings/settings.scss
- client/app/utils/featureFlags.js
* To enable add `?ft=kwfilter` to the end of the URL
> Added stub for keyword filter behind feature flag

- client/app/components/Settings/Settings.js
- client/app/components/Settings/settings.scss
- client/app/constants/index.js
Fixes #107 
FYI @rahulbot -- planning on releasing next week. Have a nice weekend!
> Set filter expand/collapse background color to white

- client/app/components/App/app.scss
- client/app/components/Register/Register.js
- client/app/components/Register/register.scss
- client/app/components/Register/registerSteps/CouhesMessage.js
- client/app/components/Settings/settings.scss
- client/app/constants/index.js
* refactored checkbox styles to `app.scss`
* added disabled state to disabled scss (ultimately it would be better to actually disable the other buttons--tech debt)
> Added confirm age to registration

- client/app/components/Post/Content.js
- client/app/components/Post/ContentFacebook.js
- client/app/components/Post/ContentTwitter.js
- client/app/components/Post/Head.js
- client/app/components/Post/HeadFacebook.js
- client/app/components/Post/HeadTwitter.js
- client/app/components/Post/Post.js
- client/app/constants/index.js
* Refactored posts into Facebook and Twitter versions
Fixes #48
> Fixed "undefined" Facebook title

- client/app/actions/socialMediaLogin.js
- client/app/components/Profile/PlatformConnected.js
- client/app/components/Profile/PlatformUnconnected.js
- client/app/components/Profile/Profile.js
- client/app/components/Register/registerSteps/SocialAuth.js
- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- client/app/components/TwitterCallback/TwitterCallback.js
- client/app/reducers/index.js
- client/app/reducers/socialMediaLogin.js
- client/app/utils/apiRequests.js
- client/app/utils/featureFlags.js
- server/config/configTemplate.py
- server/views/social_auth.py
* Added verify_mastodon endpoint
* Added mastodon config settings
* Added prototype mastodon connection UI behind feature flag (`ft=mastodon`)
TODO:
> Added Mastodon Login UI (feature flagged)

- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- migrations/versions/320fcc15decf_.py
- server/config/configTemplate.py
- server/models.py
- server/views/social_auth.py
> Added support for all mastodon instances

- client/app/components/Post/ContentMastodon.js
- client/app/components/Post/HeadMastodon.js
- client/app/components/Post/Post.js
- client/app/components/Post/PostFooter.js
- client/app/components/Post/post.scss
- client/package.json
- server/models.py
- server/scripts/queue_user_posts.py
- server/scripts/tasks.py
- server/views/social_auth.py
TODO:
Defer:
- Show "unlisted" posts too?
- Mastodon post analysis 
- Mastodon Icon
> Ingest mastodon posts and display them

- client/app/components/App/App.js
- client/app/components/MastodonAuthComplete/MastodonAuthComplete.js
- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- client/app/reducers/socialMediaLogin.js
- client/app/utils/url.js
- server/config/configTemplate.py
- server/views/home.py
- server/views/social_auth.py
> Added Mastodon specific redirect page

- server/models.py
- server/scripts/analyze_modules.py
- server/scripts/tasks.py
* Refactored URL fetching into post models
Fixes #140
> Added news score for mastodon posts

- server/models.py
- server/scripts/tasks.py
> Keep unlisted Mastodon posts

- server/models.py
- server/scripts/analyze_modules.py
> Refactored post interaction counts into Post models

- client/app/components/Profile/Profile.js
- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- client/app/constants/index.js
- server/models.py
> Poll mastodon service for authorization status

- client/app/actions/feed.js
- client/app/components/Feed/Feed.js
- client/app/components/Post/BackOfPost.js
- client/app/components/Settings/Settings.js
- client/app/components/SettingsItem/SettingsItem.js
- client/app/constants/index.js
- client/app/reducers/feed.js
- client/app/utils/featureFlags.js
- client/app/utils/filtering.js
- client/app/utils/filtering.test.js
> Added feature flag for keyword rule along with sample rules

- client/app/actions/feed.js
- client/app/reducers/feed.js
- client/app/utils/apiRequests.js
- server/views/feed.py
* Added feed/get_rules
* Added feed/toggle_rules
* Refactored client to use endpoints
Fixes #160
> Add stubbed rules endpoints

- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- client/app/constants/index.js
> Update Mastodon description

- client/app/components/SocialMediaButtons/SocialMediaButtons.js
* Clicking away from input will set instance
* Button will update with instance name
* Input will be cleared after domain set
Fixes #173
> Updated Mastodon instance select component

- client/app/components/Profile/Profile.js
- client/app/components/SocialMediaButtons/SocialMediaButtons.js
- client/app/constants/index.js
- client/app/utils/featureFlags.js
> Removed mastodon feature flag

- client/app/components/Post/BackOfPost.js
- client/app/components/Post/PostFooter.js
- client/app/components/Settings/MuteAllMenWhy.js
- client/app/components/Settings/Settings.js
- client/app/components/Settings/settings.scss
- client/app/components/SettingsItem/SettingsItem.js
- client/app/utils/filtering.js
- client/package.json
- client/webpack/webpackConfigDev.js
- client/webpack/webpackConfigProd.js
- migrations/versions/5e47480e9575_add_keyword_rule.py
- server/commands/commands.py
- server/factory.py
- server/models.py
- server/views/feed.py
> Added models for keyword rules and rule creation and sharing commands

- server/config/configTemplate.py
- server/models.py
- server/views/auth.py
> Added ENABLE_AUTO_SHARE_RULES feature flag for auto sharing gobo rules

- client/app/actions/feed.js
- client/app/components/Feed/Feed.js
- client/app/components/Feed/feed.scss
- client/app/components/Post/Head.js
- client/app/components/Post/HiddenPost.js
- client/app/components/Post/Post.js
- client/app/components/Post/PostFooter.js
- client/app/components/Post/post.scss
- client/app/components/Settings/Settings.js
- client/app/constants/index.js
- client/app/reducers/feed.js
- client/app/utils/featureFlags.js
- client/app/utils/filtering.js
- client/app/utils/misc.js
* feature flagged by `showfiltered`
> Displaying filtered out posts in default view

- client/app/components/Feed/Feed.js
- client/app/components/Post/HiddenPost.js
- client/app/components/Post/Post.js
- client/app/components/Post/post.scss
> Added click to expand filtered posts

- client/app/components/Post/PostFooter.js
* Replaced `?` icon with text for flipping to back of post
* Action list is hidden on small screens
> Added text for flipping post

- client/app/components/Settings/settings.scss
> Center rules text and icon

- client/app/components/Post/post.scss
> Center filter icons and platform logo

- client/app/components/Post/HiddenPost.js
- client/app/components/Post/post.scss
> Hidden reasons overflow to ellipsis

- migrations/versions/1266f69d6574_remove_politics_registration.py
- server/enums.py
- server/models.py
> Remove political registration from user model, echo_range from settings

- client/app/components/Settings/Settings.js
> Toggling mute all men goes between default ratio or 100%

- client/app/utils/filtering.js
> Gender ratio remains constants regardless of filters

- client/app/components/Settings/Settings.js
> Hard-code tech perspectives rule

- client/app/components/Settings/Settings.js
- migrations/env.py
- migrations/versions/8f8083a8ad61_additive_names.py
- server/commands/commands.py
- server/models.py
> Support additive filters by category name

- client/app/components/Post/Head.js
- client/app/components/Post/HeadFacebook.js
- client/app/components/Post/HeadMastodon.js
- client/app/components/Post/HeadTwitter.js
> Platform logo links to post

- server/scripts/analyze_modules.py
Adds back in code that was accidentally removed in #263
> Fix setting news score on posts

- client/app/components/App/app.scss
- client/app/components/Feed/Feed.js
- client/app/components/OverviewVis/OverviewVis.js
- client/app/components/OverviewVis/OverviewVis.scss
- client/app/utils/featureFlags.js
Hidden behind the `overview` feature flag
> Added experimental feed overview

- client/app/components/App/app.scss
- client/app/components/Feed/Feed.js
- client/app/components/Feed/feed.scss
- client/app/components/Settings/Settings.js
- client/app/components/Settings/settings.scss
- client/app/components/SettingsItem/SettingsItem.js
- client/package.json
> Position rules at top for small screens

- client/app/components/Feed/Feed.js
- client/app/components/OverviewVis/OverviewVis.js
- client/app/components/OverviewVis/OverviewVis.scss
- client/app/components/Settings/settings.scss
- client/package.json
* moved overview to be above the rules
> Overview now shows visible posts (normal and additive)

- client/app/components/Nav/nav.scss
> Shrink padding around navbar on small devices

- client/app/actions/feed.js
- client/app/actions/post.js
- client/app/components/Feed/Feed.js
- client/app/components/Post/Post.js
- client/app/components/Settings/MuteAllMenWhy.js
- client/app/components/Settings/Settings.js
- client/app/components/SettingsItem/SettingsItem.js
- client/app/middlewares/trackingMiddleware.js
- client/app/store.js
> Added eventing for controls

- migrations/versions/580b1372edb5_last_active.py
- server/models.py
- server/scripts/queue_prioritized_user_posts.py
- server/views/feed.py
* Use mastodon to determine if platform is connected too
> Added use last active in determining prioritized users

- server/models.py
Reverts mitmedialab/gobo#279
* Needed behinds the scenes
> Revert "Removed dead user model code"

- client/app/components/Feed/Feed.js
- client/app/components/Tour/Tour.js
- client/app/utils/featureFlags.js
- client/package.json
> Added guided tour infrastructure (behind feature flag)

- client/app/components/Tour/Tour.js
- client/package.json
> Added local storage to track tour completion

- client/app/components/App/app.scss
- client/app/components/Feed/Feed.js
- client/app/components/OverviewVis/OverviewVis.js
- client/app/components/OverviewVis/OverviewVis.scss
- client/app/utils/featureFlags.js
- client/package.json
> Re-positioned overview visualization and removed feature flag
